dist: xenial
language: python
python:
  - 2.7
  - 3.7
env:
  - CONDA_VERSION=4.5.x
  - CONDA_VERSION=master
matrix:
  fast_finish: true
  exclude:
    - python: 2.7
      env: CONDA_VERSION=4.5.x
  include:
    - python: 3.7
      env:
        - FLAKE8=true
        - CONDA_VERSION=4.5.x
      dist: xenial
    - python: 3.7
      env:
        - DOCS=true
        - CONDA_VERSION=master
      dist: xenial
  allow_failures:
    - env:
        - FLAKE8=true
        - CONDA_VERSION=4.5.x
      python: 3.7
    - python: 3.7
      env:
        - DOCS=true
        - CONDA_VERSION=master

addons:
  apt:
    packages:
    - attr
    - mercurial

install:
  # show which shell we are running
  - ps -ef | grep $$
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p /opt/conda
  - mkdir /opt/conda/locks
  # make central lock directory not writable to simulate central "all-users" install
  - chmod -w /opt/conda/locks
  - if [ "$CONDA_VERSION" = "4.5.x" ]; then
        git clone -b $CONDA_VERSION --single-branch --depth 1000 https://github.com/conda/conda.git;
        pushd conda;
        /opt/conda/bin/python -m conda init --dev;
        hash -r;
        conda info;
        popd;
    else
        git clone -b $CONDA_VERSION --single-branch --depth 1000 https://github.com/conda/conda.git;
        pushd conda;
        /opt/conda/bin/python -m conda init --dev bash;
        hash -r;
        conda info;
        popd;
    fi
  - export PATH=/opt/conda/bin:$PATH
  - source /opt/conda/bin/activate
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  # - conda config --add create_default_packages nomkl
  - conda info
  # avoids a python 3.7 problem
  - conda install -q cytoolz
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install -q futures scandir;
    fi
  - conda install -q anaconda-client requests filelock contextlib2 jinja2 patchelf
  - conda install -q pyflakes beautifulsoup4 chardet pycrypto glob2 psutil pytz tqdm conda-package-handling py-lief
  - pip install pkginfo
  - if [[ "$FLAKE8" == "true" ]]; then
      conda install -q flake8;
    elif [[ "$DOCS" == "true" ]]; then
      pip install -r requirements-docs.txt;
    else
      conda install -c c3i_test -q perl;
      conda install -q pytest pip pytest-cov pytest-forked pytest-xdist nomkl numpy mock pytest-mock;
      pushd .. && git clone https://github.com/conda/conda_build_test_recipe && popd;
    fi
  - pip install --no-deps .
  - conda info -a

script: ./ci/travis/run.sh

notifications:
    flowdock: ef3821a08a791106512ccfc04c92eccb

git:
  depth: 10000

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
